const Student = require('../models/Student');
const Course = require('../models/Course');
const College = require('../models/College');
const Slot = require('../models/Slot');
const User = require('../models/User');
const bcrypt = require('bcryptjs');

// Create a new student
exports.createStudent = async (req, res) => {
  const { email } = req.body;
  try {
    const { rollNumber, name, courseId, dob } = req.body;
    const userId = req.user.id;
    const userRole = req.user.role;

    if (!email || !dob) {
      return res.status(400).json({ message: 'Email and date of birth (dob) are required' });
    }

    // Check if user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ message: 'A user with this email already exists' });
    }

    // If moderator, verify they are associated with the college
    let moderatorCollege = null;
    if (userRole === 'moderator') {
      moderatorCollege = await College.findOne({ moderatorId: userId });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
    }

    // Verify that the course exists
    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(400).json({ message: 'Course not found' });
    }

    // If moderator, verify the course belongs to their college
    if (userRole === 'moderator') {
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      if (course.collegeId.toString() !== moderatorCollege._id.toString()) {
        return res.status(403).json({ message: 'Moderators can only create students for courses in their own college' });
      }
    }

    // Create Student profile. User account is autogenerated via pre-save hook in Student model.
    const student = new Student({ 
      rollNumber, 
      name, 
      email, 
      dob: new Date(dob),
      courseId
    });
    await student.save();

    // Determine raw password to send back to frontend
    let rawPassword;
    if (typeof dob === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(dob.split('T')[0])) {
      rawPassword = dob.split('T')[0].replace(/-/g, '');
    } else {
      const dateObj = new Date(dob);
      const yyyy = dateObj.getUTCFullYear();
      const mm = String(dateObj.getUTCMonth() + 1).padStart(2, '0');
      const dd = String(dateObj.getUTCDate()).padStart(2, '0');
      rawPassword = `${yyyy}${mm}${dd}`;
    }

    res.status(201).json({ student, userPassword: rawPassword });
  } catch (error) {
    // Cleanup orphaned user account if student save failed after user was saved in pre-save hook
    if (email) {
      try {
        const orphanedUser = await User.findOne({ email, role: 'student' });
        if (orphanedUser) {
          const studentExists = await Student.findOne({ userId: orphanedUser._id });
          if (!studentExists) {
            await User.findByIdAndDelete(orphanedUser._id);
          }
        }
      } catch (cleanupErr) {
        console.error('Failed to cleanup orphaned user:', cleanupErr);
      }
    }
    if (error.code === 11000) {
      return res.status(400).json({ message: 'Student with this roll number already exists in the course' });
    }
    res.status(500).json({ message: error.message });
  }
};

// Get all students
exports.getAllStudents = async (req, res) => {
  try {
    const userId = req.user.id;
    const userRole = req.user.role;

    let filter = {};
    if (userRole === 'moderator') {
      const moderatorCollege = await College.findOne({ moderatorId: userId });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      // Get courses for this college, then students in those courses
      const courses = await Course.find({ collegeId: moderatorCollege._id });
      const courseIds = courses.map(c => c._id);
      filter = { courseId: { $in: courseIds } };
    }

    const students = await Student.find(filter).populate('courseId', 'courseCode');
    res.status(200).json(students);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get student by ID
exports.getStudentById = async (req, res) => {
  try {
    const student = await Student.findById(req.params.id).populate('courseId', 'courseCode');
    if (!student) {
      return res.status(404).json({ message: 'Student not found' });
    }

    // If moderator, verify the student's course belongs to their college
    const userRole = req.user.role;
    if (userRole === 'moderator') {
      const moderatorCollege = await College.findOne({ moderatorId: req.user.id });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      if (student.courseId === null || !student.courseId.collegeId) {
        // Populate might not have populated the collegeId, so we need to fetch the course
        const course = await Course.findById(student.courseId);
        if (!course) {
          return res.status(404).json({ message: 'Course not found' });
        }
        if (course.collegeId.toString() !== moderatorCollege._id.toString()) {
          return res.status(403).json({ message: 'Moderators can only access students from courses in their own college' });
        }
      } else {
        // If the course object is populated with collegeId
        if (student.courseId.collegeId.toString() !== moderatorCollege._id.toString()) {
          return res.status(403).json({ message: 'Moderators can only access students from courses in their own college' });
        }
      }
    }

    res.status(200).json(student);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Update student by ID
exports.updateStudent = async (req, res) => {
  try {
    const { rollNumber, name, courseId, email, dob } = req.body;
    const userId = req.user.id;
    const userRole = req.user.role;

    // If moderator, get their college
    let moderatorCollege = null;
    if (userRole === 'moderator') {
      moderatorCollege = await College.findOne({ moderatorId: userId });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
    }

    // If courseId is provided, verify it exists
    if (courseId) {
      const course = await Course.findById(courseId);
      if (!course) {
        return res.status(400).json({ message: 'Course not found' });
      }
      // If moderator, verify the course belongs to their college
      if (userRole === 'moderator') {
        if (!moderatorCollege) {
          return res.status(404).json({ message: 'College not found for this moderator' });
        }
        if (course.collegeId.toString() !== moderatorCollege._id.toString()) {
          return res.status(403).json({ message: 'Moderators can only update students for courses in their own college' });
        }
      }
    }

    const student = await Student.findById(req.params.id);
    if (!student) {
      return res.status(404).json({ message: 'Student not found' });
    }

    // If moderator, verify the student's course belongs to their college
    if (userRole === 'moderator') {
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      const course = await Course.findById(student.courseId);
      if (!course || course.collegeId.toString() !== moderatorCollege._id.toString()) {
        return res.status(403).json({ message: 'Moderators can only access students from courses in their own college' });
      }
    }

    // Update the associated User record if details are changing
    if (student.userId) {
      const userUpdate = {};
      if (name) userUpdate.name = name;
      if (email) userUpdate.email = email;
      if (dob) {
        let rawPassword;
        if (typeof dob === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(dob.split('T')[0])) {
          rawPassword = dob.split('T')[0].replace(/-/g, '');
        } else {
          const dateObj = new Date(dob);
          if (!isNaN(dateObj.getTime())) {
            const yyyy = dateObj.getUTCFullYear();
            const mm = String(dateObj.getUTCMonth() + 1).padStart(2, '0');
            const dd = String(dateObj.getUTCDate()).padStart(2, '0');
            rawPassword = `${yyyy}${mm}${dd}`;
          }
        }
        if (rawPassword) {
          const salt = await bcrypt.genSalt(10);
          userUpdate.password = await bcrypt.hash(rawPassword, salt);
        }
      }

      if (Object.keys(userUpdate).length > 0) {
        await User.findByIdAndUpdate(student.userId, userUpdate);
      }
    } else {
      // Autogenerate User account fallback if it doesn't exist for the student
      const userEmail = email || student.email;
      const userName = name || student.name;
      const userDob = dob || student.dob;

      let user = await User.findOne({ email: userEmail });
      if (!user) {
        let rawPassword;
        if (userDob) {
          if (typeof userDob === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(userDob.split('T')[0])) {
            rawPassword = userDob.split('T')[0].replace(/-/g, '');
          } else {
            const dateObj = new Date(userDob);
            if (!isNaN(dateObj.getTime())) {
              const yyyy = dateObj.getUTCFullYear();
              const mm = String(dateObj.getUTCMonth() + 1).padStart(2, '0');
              const dd = String(dateObj.getUTCDate()).padStart(2, '0');
              rawPassword = `${yyyy}${mm}${dd}`;
            }
          }
        }

        if (rawPassword) {
          const salt = await bcrypt.genSalt(10);
          const hashedPassword = await bcrypt.hash(rawPassword, salt);

          user = new User({
            name: userName,
            email: userEmail,
            password: hashedPassword,
            role: 'student',
            active: true
          });
          await user.save();
        }
      }
      if (user) {
        student.userId = user._id;
      }
    }

    const studentUpdate = { rollNumber, name, courseId, email };
    if (dob) studentUpdate.dob = new Date(dob);
    if (student.userId) studentUpdate.userId = student.userId;

    const updatedStudent = await Student.findByIdAndUpdate(
      req.params.id,
      studentUpdate,
      { new: true, runValidators: true }
    ).populate('courseId', 'courseCode');

    res.status(200).json(updatedStudent);
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({ message: 'Student with this roll number already exists in the course' });
    }
    res.status(500).json({ message: error.message });
  }
};

// Delete student by ID
exports.deleteStudent = async (req, res) => {
  try {
    const userId = req.user.id;
    const userRole = req.user.role;

    // Find the student first to check course
    const student = await Student.findById(req.params.id).populate('courseId');
    if (!student) {
      return res.status(404).json({ message: 'Student not found' });
    }

    // If moderator, verify the student's course belongs to their college
    if (userRole === 'moderator') {
      const moderatorCollege = await College.findOne({ moderatorId: userId });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      if (student.courseId === null || !student.courseId.collegeId) {
        // Populate might not have populated the collegeId, so we need to fetch the course
        const course = await Course.findById(student.courseId);
        if (!course) {
          return res.status(404).json({ message: 'Course not found' });
        }
        if (course.collegeId.toString() !== moderatorCollege._id.toString()) {
          return res.status(403).json({ message: 'Moderators can only delete students from courses in their own college' });
        }
      } else {
        // If the course object is populated with collegeId
        if (student.courseId.collegeId.toString() !== moderatorCollege._id.toString()) {
          return res.status(403).json({ message: 'Moderators can only delete students from courses in their own college' });
        }
      }
    }

    // Delete the associated user account if it exists
    if (student.userId) {
      await User.findByIdAndDelete(student.userId);
    }

    const studentDeleted = await Student.findByIdAndDelete(req.params.id);
    if (!studentDeleted) {
      return res.status(404).json({ message: 'Student not found' });
    }

    res.status(200).json({ message: 'Student deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get students belonging to a particular course
exports.getStudentByCourse = async (req, res) => {
  try {
    const { courseId } = req.params;
    const userId = req.user.id;
    const userRole = req.user.role;

    // Verify that the course exists
    const course = await Course.findById(courseId);
    if (!course) {
      return res.status(404).json({ message: 'Course not found' });
    }

    // If moderator, verify the course belongs to their college
    if (userRole === 'moderator') {
      const moderatorCollege = await College.findOne({ moderatorId: userId });
      if (!moderatorCollege) {
        return res.status(404).json({ message: 'College not found for this moderator' });
      }
      if (course.collegeId.toString() !== moderatorCollege._id.toString()) {
        return res.status(403).json({ message: 'Moderators can only access students from courses in their own college' });
      }
    }

    const students = await Student.find({ courseId }).populate('courseId', 'courseCode');
    res.status(200).json(students);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get attendance for currently logged-in student
exports.getMyAttendance = async (req, res) => {
  try {
    const userId = req.user.id;
    const userRole = req.user.role;

    if (userRole !== 'student') {
      return res.status(403).json({ message: 'Access denied: Only students can access this route' });
    }

    // 1. Find the student profile using userId
    const student = await Student.findOne({ userId });
    if (!student) {
      return res.status(404).json({ message: 'Student profile not found for this user' });
    }

    // 2. Find all completed/attendance-taken slots for the student's course
    const slots = await Slot.find({
      courseId: student.courseId,
      attendanceTaken: true
    }).populate('trainerId', 'name').sort({ date: 1, startTime: 1 });

    // 3. Process attendance history
    const attendanceRecords = slots.map(slot => {
      const isPresent = slot.presentStudents.includes(student.rollNumber);
      return {
        slotId: slot._id,
        date: slot.date,
        startTime: slot.startTime,
        endTime: slot.endTime,
        topic: slot.topic || 'N/A',
        roomNo: slot.roomNo,
        trainerName: slot.trainerId ? slot.trainerId.name : 'N/A',
        present: isPresent
      };
    });

    // 4. Calculate summary stats
    const totalClasses = attendanceRecords.length;
    const attendedClasses = attendanceRecords.filter(r => r.present).length;
    const absentClasses = totalClasses - attendedClasses;
    const attendancePercentage = totalClasses > 0 ? parseFloat(((attendedClasses / totalClasses) * 100).toFixed(2)) : 0;

    res.status(200).json({
      student: {
        id: student._id,
        name: student.name,
        rollNumber: student.rollNumber,
        courseId: student.courseId
      },
      summary: {
        totalClasses,
        attendedClasses,
        absentClasses,
        attendancePercentage
      },
      records: attendanceRecords
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
