services:
  database:
    image: mongo:6.0
    container_name: tpc_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tpc_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://database:27017/mern-db 
      - JWT_SECRET=authoristion-token-stuff-to-randomize
    networks:
      - mern-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tpc_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
